### ISSUE TITLE
Project dosen't compile

### ISSUE THREAD

**Issue by MahakalaPL** [ylboerner/easyPokerHUD#7]
The are some .cs files missing in solution.
![image](https://user-images.githubusercontent.com/66013904/83016279-fa2f7300-a021-11ea-9b80-1b4ca5b6391c.png)

**Comment by MahakalaPL** [comment]
I will decompile working wersion and try to add missing files :)

**Comment by ylboerner** [comment]
@MahakalaPL You are very welcome to do that! Thank you :-)

**Comment by morrisok69** [comment]
Any update on those missing files?

**Comment by 1800CODENOW** [comment]
Same issue for me, gonna try as suggested, decompile. I plan to add some updates to this project such as overlay and statistics.

**Comment by 1800CODENOW** [comment]
@ylboerner Do you have an email or discord or something we can touch base with, I am extremely interested in enhancing this project as me and my friends use it. I have have extensive experience with data gathering, C# and some basic math knowledge from college.

**Comment by ylboerner** [comment]
@1800CODENOW Hello, absolutely! I sent you an invite to the official Slack channel via email. We can discuss everything there.

**Comment by Xvidia123** [comment]
Is there some solution to this Issue yet or is that project totally dead?

**Comment by ylboerner** [comment]
@Xvidia123 Hi, this project is beyond dead 😉 Feel free to exhume it! The code for parsing should still work.
