### ISSUE TITLE
The downloaded version doesnt display HUD on Pokerstars?

### ISSUE THREAD

**Issue by sword134** [ylboerner/easyPokerHUD#8]
Hello,
I am using the already prebuilt version from your website. All setup (handhistory and seating) has been done accordingly. It says with greentext that it is running for pokerstars, however no HUD appears.

I want to ask if it still works for pokerstars. I am on Windows 8.1 and I know you say windows 10 is required. But if there is any package I am missing it isn't telling me.

**Comment by girorme** [comment]
> Hello,
> I am using the already prebuilt version from your website. All setup (handhistory and seating) has been done accordingly. It says with greentext that it is running for pokerstars, however no HUD appears.
> 
> I want to ask if it still works for pokerstars. I am on Windows 8.1 and I know you say windows 10 is required. But if there is any package I am missing it isn't telling me.

Here the same. Using windows 10 but  hud doesnt appears

**Comment by ylboerner** [comment]
@sword134 @girorme Hi guys, I'm super sorry but this project has been dead for a while. Simply no time to maintain it 😢
